title: NeuroGPT
description: Natural Language-guided Neural Encoding Benchmark for Vision
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

github:
  is_project_page: true
  repository_url: https://github.com/neurogpt/neurogpt.github.io
